language: python

python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run web sh -c "python3 manage.py makemigrations"
  - docker-compose run web sh -c "python3 manage.py migrate"
  - docker-compose run web sh -c "python3 manage.py loaddata data/0001_seed_data_to_database.json"
  - docker-compose run web sh -c "python3 manage.py test auctions/tests"
